from app.core.project_config import get_project_config
from app.services.chat_patterns import ALEX_TERMS as ALEX_TERMS

_PROJECT_CONFIG = get_project_config()
_OWNER_REFERENCE = _PROJECT_CONFIG.assistant.owner_reference

ALEX_PROFILE_TERMS = (
    "experience",
    "skill",
    "skills",
    "hard skill",
    "hard skills",
    "soft skill",
    "soft skills",
    "strength",
    "strengths",
    "strong side",
    "strong sides",
    "advantage",
    "different",
    "project",
    "projects",
    "resume",
    "cv",
    "education",
    "university",
    "degree",
    "master",
    "master's",
    "masters",
    "mba",
    "academic",
    "honours",
    "scholarship",
    "finance",
    "banking",
    "insurance",
    "work",
    "worked",
    "career",
    "background",
    "intro",
    "profile",
    "portfolio",
    "summary",
    "github",
    "linkedin",
    "contact",
    "availability",
    "available",
    "start",
    "hire",
    "role",
    "stack",
    "python",
    "fastapi",
    "automation",
    "rag",
    "qdrant",
    "prometheus",
    "grafana",
    "observability",
    "metrics",
    "monitoring",
    "backend",
    "api",
    "website",
    "web app",
    "software",
    "program",
    "internal tool",
    "chatbot",
    "collaboration",
    "service",
    "services",
    "integration",
    "right to work",
    "work authorisation",
    "work authorization",
    "share code",
    "uk location",
    "based in the uk",
    "visa",
    "employment eligibility",
    "work permit",
)

SERVICE_REQUEST_TERMS = (
    "build a website",
    "create a website",
    "make a website",
    "need a website",
    "need a program",
    "need a tool",
    "need an internal tool",
    "need software",
    "build a tool",
    "build software",
    "create software",
    "build an app",
    "create an app",
    "automation project",
    "automate my",
    "automate our",
    "api integration",
    "integrate api",
    "internal tool",
    "business automation",
    "rag chatbot",
    "ai assistant",
    f"can {_OWNER_REFERENCE.casefold()} build",
    "can he build",
)

WEAKNESS_REQUEST_TERMS = (
    "weakness",
    "weaknesses",
    "education",
    "university",
    "degree",
    "master",
    "master's",
    "masters",
    "mba",
    "academic",
    "honours",
    "scholarship",
    "finance",
    "banking",
    "insurance",
    "rag",
    "qdrant",
    "prometheus",
    "grafana",
    "observability",
    "metrics",
    "monitoring",
    "weak point",
    "weak points",
    "development area",
    "development areas",
    "areas to improve",
    "limitations",
    f"what should {_OWNER_REFERENCE.casefold()} improve",
    "what should he improve",
)

SECOND_PERSON_TERMS = (
    "you",
    "your",
    "yours",
)

FOLLOW_UP_PRONOUN_TERMS = (
    "he",
    "him",
    "his",
)

FOLLOW_UP_PROFILE_TERMS = (
    "background",
    "career",
    "do",
    "does",
    "experience",
    "profile",
    "project",
    "projects",
    "skill",
    "skills",
    "soft",
    "hard",
    "tell",
    "work",
    "availability",
    "available",
    "start",
    "hire",
    "stack",
    "service",
    "services",
    "website",
    "software",
    "automation",
    "strength",
    "strengths",
    "different",
    "weakness",
    "weaknesses",
)

SHORT_CONTINUATION_PATTERNS = (
    "yes",
    "yes please",
    "sure",
    "please",
    "go ahead",
    "so tell me",
    "tell me",
    "go on",
    "continue",
    "more",
    "more please",
)

CONTACT_OR_AVAILABILITY_TERMS = (
    "contact",
    "connect",
    "speak",
    "talk",
    "chat",
    "hire",
    "offer",
    "availability",
    "available",
    "start",
    "start date",
    "new job",
    "right to work",
    "work authorisation",
    "work authorization",
    "share code",
    "uk work",
    "uk location",
    "based in the uk",
    "visa",
    "employment eligibility",
    "work permit",
)

KNOWN_THIRD_PARTY_SUBJECTS = ("elon musk",)

EDUCATION_PROFILE_TERMS = (
    "academic",
    "banking",
    "degree",
    "education",
    "finance",
    "honours",
    "insurance",
    "master",
    "master's",
    "masters",
    "mba",
    "scholarship",
    "university",
)

RAG_PROJECT_TERMS = (
    "grafana",
    "metrics",
    "monitoring",
    "observability",
    "prometheus",
    "qdrant",
    "rag",
    "retrieval augmented",
    "vector search",
)

BROAD_EDUCATION_REWRITE_TERMS = (
    "mba",
    "university",
    "degree",
    "master",
    "master's",
    "education",
    "finance",
    "banking",
    "insurance",
)

RAG_REWRITE_TERMS = ("rag", "qdrant", "embedding")

OBSERVABILITY_REWRITE_TERMS = (
    "prometheus",
    "grafana",
    "observability",
    "metrics",
)

SERVICE_REWRITE_TERMS = ("service", "website", "software")
